### ISSUE TITLE
Lambda Function Issue

### ISSUE THREAD

**Issue by maans2001** [Pizzaface/Alexa-Chromecast-Skill-2.0#13] opened 2017-07-26 18:34 UTC
I'm trying to install this skill for 3 days and I'm just getting errors and fixing them but now i'm stuck on this

When I'm running aws-setup.sh 

it says

Creating AmazonAlexaSkill role.
Creating AlexaChromecastSkillCommands topic.
Creating AlexaChromecastSkill lambda function.
/usr/bin/env: bash -e: No such file or directory

I don't know what is the problem here

**Comment by Makr91** [comment] 2017-07-30 08:28
I am getting similar when trying the same with 

root@ha:/home/pi/Alexa-Chromecast-Skill-2.0#  ./start.sh
./start.sh: line 7: .env: No such file or directory


With or without sudo, bash start.sh , sh start.sh etc

**Comment by waxhell** [comment] 2017-08-03 07:08
I had to use the following workaround, but note that I am not running on a RPi, but rather a Pogoplug_E02 running Arch Linux. I figured it was because my environment was different.

Updated the first line of all of the scripts to use the following:

```#!/usr/bin/bash -e```

rather than the default 

```#!/usr/bin/env bash -e```

**Comment by CoryPulm** [comment] 2017-08-20 02:46
Confirmed, even on raspi this error occurs, switching to
`#!/bin/bash -e`
instead works on latest Raspbian (Stretch) as well

**Comment by rafiahmad1980** [comment] 2017-09-08 15:41
I faced the issue and had to replace "#!/usr/bin/env bash -e" with "#!/bin/bash -e" in all .sh files while installing on my Raspberry pi 3. There should be a better fix of this issue which can switch bash depending upon the OS.

**Comment by jinxo13** [comment] 2020-07-12 22:21
Changed in the latest release to use #!/bin/bash.

Recommend closing.

**Closed** 2020-07-22 08:37 UTC
